name: Python Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # You can adjust this if you use pytest/unittest
        if [ -d "tests" ]; then
          pytest
        else
          echo "No tests directory found, skipping tests"
        fi

    - name: Check code formatting (optional)
      run: |
        pip install black
        black --check .

    - name: Lint with flake8 (optional)
      run: |
        pip install flake8
        flake8 . --exclude=venv,__pycache__

